package mx.certipass.ws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * Web Service de Insigna
 *
 * This class was generated by Apache CXF 3.1.12
 * 2017-08-28T12:56:23.051-05:00
 * Generated source version: 3.1.12
 * 
 */
@WebService(targetNamespace = "http://ws.certipass.mx/", name = "InsignaSOAPWS")
@XmlSeeAlso({ObjectFactory.class})
public interface InsignaSOAPWS {

    /**
     * Método de validación de CFDI.
     */
    @WebMethod
    @RequestWrapper(localName = "validateCfdi", targetNamespace = "http://ws.certipass.mx/", className = "mx.certipass.ws.ValidateCfdi")
    @ResponseWrapper(localName = "validateCfdiResponse", targetNamespace = "http://ws.certipass.mx/", className = "mx.certipass.ws.ValidateCfdiResponse")
    @WebResult(name = "return", targetNamespace = "http://ws.certipass.mx/")
    public mx.certipass.ws.CfdiValidateResult validateCfdi(
        @WebParam(name = "validateCfdiWrapper", targetNamespace = "http://ws.certipass.mx/")
        mx.certipass.ws.ValidateCfdiWrapper validateCfdiWrapper
    ) throws OperationFailedException;

    /**
     * Método para verificar una operación.
     */
    @WebMethod
    @RequestWrapper(localName = "verifyOperation", targetNamespace = "http://ws.certipass.mx/", className = "mx.certipass.ws.VerifyOperation")
    @ResponseWrapper(localName = "verifyOperationResponse", targetNamespace = "http://ws.certipass.mx/", className = "mx.certipass.ws.VerifyOperationResponse")
    @WebResult(name = "return", targetNamespace = "http://ws.certipass.mx/")
    public mx.certipass.ws.OperationVerifyResult verifyOperation(
        @WebParam(name = "verifyOperationWrapper", targetNamespace = "http://ws.certipass.mx/")
        mx.certipass.ws.VerifyOperationWrapper verifyOperationWrapper
    ) throws OperationFailedException;

    /**
     * Método para obtener la información de un cfdi timbrado.
     */
    @WebMethod
    @RequestWrapper(localName = "getCfdiInfo", targetNamespace = "http://ws.certipass.mx/", className = "mx.certipass.ws.GetCfdiInfo")
    @ResponseWrapper(localName = "getCfdiInfoResponse", targetNamespace = "http://ws.certipass.mx/", className = "mx.certipass.ws.GetCfdiInfoResponse")
    @WebResult(name = "return", targetNamespace = "http://ws.certipass.mx/")
    public mx.certipass.ws.CfdiInfoResult getCfdiInfo(
        @WebParam(name = "cfdiInfoWrapper", targetNamespace = "http://ws.certipass.mx/")
        mx.certipass.ws.CfdiInfoWrapper cfdiInfoWrapper
    ) throws OperationFailedException;

    /**
     * Método para timbrar un CFDI.
     */
    @WebMethod
    @RequestWrapper(localName = "signCfdi", targetNamespace = "http://ws.certipass.mx/", className = "mx.certipass.ws.SignCfdi")
    @ResponseWrapper(localName = "signCfdiResponse", targetNamespace = "http://ws.certipass.mx/", className = "mx.certipass.ws.SignCfdiResponse")
    @WebResult(name = "return", targetNamespace = "http://ws.certipass.mx/")
    public mx.certipass.ws.CfdiSignResult signCfdi(
        @WebParam(name = "cfdiSignWrapper", targetNamespace = "http://ws.certipass.mx/")
        mx.certipass.ws.CfdiSignWrapper cfdiSignWrapper
    ) throws OperationFailedException;

    /**
     * Método para cancelar un CFDI.
     */
    @WebMethod
    @RequestWrapper(localName = "cancelCfdi", targetNamespace = "http://ws.certipass.mx/", className = "mx.certipass.ws.CancelCfdi")
    @ResponseWrapper(localName = "cancelCfdiResponse", targetNamespace = "http://ws.certipass.mx/", className = "mx.certipass.ws.CancelCfdiResponse")
    @WebResult(name = "return", targetNamespace = "http://ws.certipass.mx/")
    public mx.certipass.ws.CfdiCancelResult cancelCfdi(
        @WebParam(name = "cfdiCancelWrapper", targetNamespace = "http://ws.certipass.mx/")
        mx.certipass.ws.CfdiCancelWrapper cfdiCancelWrapper
    ) throws OperationFailedException;
}
