package mx.certipass.ws;

import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.1.12
 * 2017-08-28T12:56:23.084-05:00
 * Generated source version: 3.1.12
 * 
 */
@WebServiceClient(name = "InsignaSOAPWSService", 
                  wsdlLocation = "C:/X/INSIGNAWS.wsdl",
                  targetNamespace = "http://ws.certipass.mx/") 
public class InsignaSOAPWSService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://ws.certipass.mx/", "InsignaSOAPWSService");
    public final static QName InsignaSOAPWSPort = new QName("http://ws.certipass.mx/", "InsignaSOAPWSPort");
    static {
        URL url = InsignaSOAPWSService.class.getResource("C:/X/INSIGNAWS.wsdl");
        if (url == null) {
            url = InsignaSOAPWSService.class.getClassLoader().getResource("C:/X/INSIGNAWS.wsdl");
        } 
        if (url == null) {
            java.util.logging.Logger.getLogger(InsignaSOAPWSService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "C:/X/INSIGNAWS.wsdl");
        }       
        WSDL_LOCATION = url;
    }

    public InsignaSOAPWSService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public InsignaSOAPWSService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public InsignaSOAPWSService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public InsignaSOAPWSService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public InsignaSOAPWSService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public InsignaSOAPWSService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    




    /**
     *
     * @return
     *     returns InsignaSOAPWS
     */
    @WebEndpoint(name = "InsignaSOAPWSPort")
    public InsignaSOAPWS getInsignaSOAPWSPort() {
        return super.getPort(InsignaSOAPWSPort, InsignaSOAPWS.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns InsignaSOAPWS
     */
    @WebEndpoint(name = "InsignaSOAPWSPort")
    public InsignaSOAPWS getInsignaSOAPWSPort(WebServiceFeature... features) {
        return super.getPort(InsignaSOAPWSPort, InsignaSOAPWS.class, features);
    }

}
