
package mx.certipass.ws;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.1.12
 * 2017-08-28T12:56:23.015-05:00
 * Generated source version: 3.1.12
 */

@WebFault(name = "OperationFailed", targetNamespace = "http://ws.certipass.mx/")
public class OperationFailedException extends Exception {
    
    private mx.certipass.ws.OperationFailed operationFailed;

    public OperationFailedException() {
        super();
    }
    
    public OperationFailedException(String message) {
        super(message);
    }
    
    public OperationFailedException(String message, Throwable cause) {
        super(message, cause);
    }

    public OperationFailedException(String message, mx.certipass.ws.OperationFailed operationFailed) {
        super(message);
        this.operationFailed = operationFailed;
    }

    public OperationFailedException(String message, mx.certipass.ws.OperationFailed operationFailed, Throwable cause) {
        super(message, cause);
        this.operationFailed = operationFailed;
    }

    public mx.certipass.ws.OperationFailed getFaultInfo() {
        return this.operationFailed;
    }
}
